Rails.application.routes.draw do
  get 'dose/index'
  get 'dose/new'
  get 'dose/create'
  get 'dose/destroy'
  get 'dose/show'
  get 'dose/edit'
  get 'dose/update'
  get 'ingredient/index'
  get 'ingredient/new'
  get 'ingredient/create'
  get 'ingredient/destroy'
  get 'ingredient/show'
  get 'ingredient/edit'
  get 'ingredient/update'
  get 'cocktail/index'
  get 'cocktail/new'
  get 'cocktail/create'
  get 'cocktail/destroy'
  get 'cocktail/show'
  get 'cocktail/edit'
  get 'cocktail/update'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
